create table if not exists public.course_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_title text not null,
  rating int not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, course_title),
  constraint course_ratings_rating_range check (rating >= 1 and rating <= 5)
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_course_ratings_updated_at on public.course_ratings;

create trigger set_course_ratings_updated_at
before update on public.course_ratings
for each row
execute function public.set_updated_at();

alter table public.course_ratings enable row level security;

create policy "Course ratings select own" on public.course_ratings
for select
using (auth.uid() = user_id);

create policy "Course ratings insert own" on public.course_ratings
for insert
with check (auth.uid() = user_id);

create policy "Course ratings update own" on public.course_ratings
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Course ratings delete own" on public.course_ratings
for delete
using (auth.uid() = user_id);
