create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.role, 'student')) = 'admin'
  );
$$;

create or replace function public.can_access_course(p_course_key text)
returns boolean
language sql
stable
as $$
  select
    public.is_admin_user()
    or exists (
      select 1
      from public.enrollments e
      where e.user_id = auth.uid()
        and e.course_title = p_course_key
        and coalesce(e.approval_status, 'approved') = 'approved'
    );
$$;

create table if not exists public.short_course_modules (
  id bigint generated by default as identity primary key,
  course_key text not null,
  title text not null,
  description text,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.short_course_lessons (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.short_course_modules(id) on delete cascade,
  title text not null,
  summary text,
  video_url text,
  documentation_url text,
  external_review_url text,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.short_course_quizzes (
  id bigint generated by default as identity primary key,
  course_key text not null,
  module_id bigint references public.short_course_modules(id) on delete set null,
  title text not null,
  description text,
  question_count int not null default 0,
  pass_score int not null default 70,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.short_course_projects (
  id bigint generated by default as identity primary key,
  course_key text not null,
  title text not null,
  description text,
  submission_instruction text,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.short_course_tests (
  id bigint generated by default as identity primary key,
  course_key text not null,
  title text not null,
  description text,
  duration_minutes int,
  pass_score int not null default 70,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.short_course_user_lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.short_course_lessons(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

create index if not exists idx_short_course_modules_course_key
  on public.short_course_modules(course_key, sort_order);

create unique index if not exists uq_short_course_modules_course_title
  on public.short_course_modules(course_key, title);

create index if not exists idx_short_course_lessons_module_id
  on public.short_course_lessons(module_id, sort_order);

create unique index if not exists uq_short_course_lessons_module_title
  on public.short_course_lessons(module_id, title);

create index if not exists idx_short_course_quizzes_course_key
  on public.short_course_quizzes(course_key, sort_order);

create unique index if not exists uq_short_course_quizzes_course_title
  on public.short_course_quizzes(course_key, title);

create index if not exists idx_short_course_projects_course_key
  on public.short_course_projects(course_key, sort_order);

create unique index if not exists uq_short_course_projects_course_title
  on public.short_course_projects(course_key, title);

create index if not exists idx_short_course_tests_course_key
  on public.short_course_tests(course_key, sort_order);

create unique index if not exists uq_short_course_tests_course_title
  on public.short_course_tests(course_key, title);

create trigger set_short_course_user_lesson_progress_updated_at
before update on public.short_course_user_lesson_progress
for each row
execute function public.set_updated_at();

alter table public.short_course_modules enable row level security;
alter table public.short_course_lessons enable row level security;
alter table public.short_course_quizzes enable row level security;
alter table public.short_course_projects enable row level security;
alter table public.short_course_tests enable row level security;
alter table public.short_course_user_lesson_progress enable row level security;

create policy "Short modules read by access" on public.short_course_modules
for select
using (public.can_access_course(course_key));

create policy "Short lessons read by access" on public.short_course_lessons
for select
using (
  exists (
    select 1
    from public.short_course_modules m
    where m.id = module_id
      and public.can_access_course(m.course_key)
  )
);

create policy "Short quizzes read by access" on public.short_course_quizzes
for select
using (public.can_access_course(course_key));

create policy "Short projects read by access" on public.short_course_projects
for select
using (public.can_access_course(course_key));

create policy "Short tests read by access" on public.short_course_tests
for select
using (public.can_access_course(course_key));

create policy "Short lesson progress select own" on public.short_course_user_lesson_progress
for select
using (auth.uid() = user_id);

create policy "Short lesson progress insert own" on public.short_course_user_lesson_progress
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.short_course_lessons l
    join public.short_course_modules m on m.id = l.module_id
    where l.id = lesson_id
      and public.can_access_course(m.course_key)
  )
);

create policy "Short lesson progress update own" on public.short_course_user_lesson_progress
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Short modules admin manage" on public.short_course_modules
for all
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "Short lessons admin manage" on public.short_course_lessons
for all
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "Short quizzes admin manage" on public.short_course_quizzes
for all
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "Short projects admin manage" on public.short_course_projects
for all
using (public.is_admin_user())
with check (public.is_admin_user());

create policy "Short tests admin manage" on public.short_course_tests
for all
using (public.is_admin_user())
with check (public.is_admin_user());

with upsert_modules as (
  insert into public.short_course_modules (course_key, title, description, sort_order)
  values
    (
      'Short Course::Basic Computer Skills',
      'Module 1: Computer Fundamentals',
      'Introduction to computers, operating systems, and file management.',
      1
    ),
    (
      'Short Course::Basic Computer Skills',
      'Module 2: Office Productivity',
      'Hands-on skills in Word, Excel, and PowerPoint for daily productivity.',
      2
    ),
    (
      'Short Course::Basic Computer Skills',
      'Module 3: Internet and Communication',
      'Online research, email, and safe internet usage practices.',
      3
    )
  on conflict (course_key, title) do update
    set description = excluded.description,
        sort_order = excluded.sort_order
  returning id, title
), all_modules as (
  select id, title
  from upsert_modules
  union all
  select id, title
  from public.short_course_modules
  where course_key = 'Short Course::Basic Computer Skills'
)
insert into public.short_course_lessons (
  module_id,
  title,
  summary,
  video_url,
  documentation_url,
  external_review_url,
  sort_order
)
select m.id,
       lesson.title,
       lesson.summary,
       lesson.video_url,
       lesson.documentation_url,
       lesson.external_review_url,
       lesson.sort_order
from all_modules m
join (
  values
    ('Module 1: Computer Fundamentals', 'Lesson 1: Understanding Computer Hardware', 'Learn the main hardware components and their roles.', 'https://www.youtube.com/watch?v=ExxFxD4OSZ0', 'https://edu.gcfglobal.org/en/computerbasics/inside-a-computer/1/', 'https://www.ibm.com/topics/computer-hardware', 1),
    ('Module 1: Computer Fundamentals', 'Lesson 2: Operating System Basics', 'Navigate files, folders, and system settings.', 'https://www.youtube.com/watch?v=26QPDBe-NB8', 'https://edu.gcfglobal.org/en/windowsbasics/about-this-tutorial/1/', 'https://support.microsoft.com/windows', 2),
    ('Module 2: Office Productivity', 'Lesson 3: Microsoft Word Essentials', 'Create, format, and save professional documents.', 'https://www.youtube.com/watch?v=R0M6m4H7YxI', 'https://support.microsoft.com/word', 'https://www.guru99.com/ms-word-tutorial.html', 1),
    ('Module 2: Office Productivity', 'Lesson 4: Excel Basics', 'Use formulas, tables, and simple data analysis.', 'https://www.youtube.com/watch?v=Vl0H-qTclOg', 'https://support.microsoft.com/excel', 'https://www.excel-easy.com/', 2),
    ('Module 3: Internet and Communication', 'Lesson 5: Internet Search and Research', 'Search efficiently and evaluate online information.', 'https://www.youtube.com/watch?v=0rR4f8z4L2M', 'https://edu.gcfglobal.org/en/internetbasics/search-better/1/', 'https://support.google.com/websearch/', 1),
    ('Module 3: Internet and Communication', 'Lesson 6: Email and Online Safety', 'Use email professionally and avoid common online threats.', 'https://www.youtube.com/watch?v=4e1BndTE6Lg', 'https://edu.gcfglobal.org/en/internetbasics/internet-safety/1/', 'https://staysafeonline.org/', 2)
) as lesson(module_title, title, summary, video_url, documentation_url, external_review_url, sort_order)
  on lesson.module_title = m.title
where not exists (
  select 1
  from public.short_course_lessons l
  where l.module_id = m.id
    and l.title = lesson.title
);

insert into public.short_course_quizzes (
  course_key,
  title,
  description,
  question_count,
  pass_score,
  sort_order
)
values (
  'Short Course::Basic Computer Skills',
  'Module Review Quiz',
  'A quiz covering all lessons in Basic Computer Skills.',
  20,
  70,
  1
)
on conflict (course_key, title) do update
  set description = excluded.description,
      question_count = excluded.question_count,
      pass_score = excluded.pass_score,
      sort_order = excluded.sort_order;

insert into public.short_course_projects (
  course_key,
  title,
  description,
  submission_instruction,
  sort_order
)
values (
  'Short Course::Basic Computer Skills',
  'Final Practical Project',
  'Create a document, spreadsheet, and short presentation from a real-world scenario.',
  'Upload your deliverables to cloud storage and submit the share links to your instructor.',
  1
)
on conflict (course_key, title) do update
  set description = excluded.description,
      submission_instruction = excluded.submission_instruction,
      sort_order = excluded.sort_order;

insert into public.short_course_tests (
  course_key,
  title,
  description,
  duration_minutes,
  pass_score,
  sort_order
)
values (
  'Short Course::Basic Computer Skills',
  'Final Competency Test',
  'Final timed test that evaluates practical and theoretical understanding.',
  60,
  75,
  1
)
on conflict (course_key, title) do update
  set description = excluded.description,
      duration_minutes = excluded.duration_minutes,
      pass_score = excluded.pass_score,
      sort_order = excluded.sort_order;
